on:
  pull_request:
    types: [ opened ]
  issue_comment:

jobs:
  pr_agent_job:
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.head_ref, 'renovate/')
    permissions:
      issues: write
      pull-requests: write
      contents: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: PR Agent action step
        id: pragent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          github_action.auto_review: "true"
          github_action.auto_describe: "true"
          github_action.auto_improve: "false"
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_REVIEWER.INLINE_CODE_COMMENTS: 'true'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions. Titles should have prefix of commitlint pattern such as `feat:`, `chore:`, `test:`, `fix:`, `ci:`, `docs:` etc'
          PR_DESCRIPTION.ADD_ORIGINAL_USER_DESCRIPTION: 'true'
          PR_DESCRIPTION.KEEP_ORIGINAL_USER_TITLE: 'true'
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMENT: 'true'
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
